export const FETCH_QUIZES_START = "FETCH_QUIZES_START";
export const FETCH_QUIZES_SUCCESS = "FETCH_QUIZES_SUCCESS";
export const FETCH_QUIZES_ERROR = "FETCH_QUIZES_ERROR";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";

export const QUIZ_SET_BUTTON = "QUIZ_SET_BUTTON";
export const QUIZ_SET_BUTTON_ID = "QUIZ_SET_BUTTON_ID";
export const QUIZ_FINISHED = "QUIZ_FINISHED";
export const QUIZ_NEXT_ANSWER = "QUIZ_NEXT_ANSWER";
export const QUIZ_SET_STATE = "QUIZ_SET_STATE";
export const QUIZ_RETRY = "QUIZ_RETRY";